// --- DATA STORE ---
const db = [
    {
        id: "gpt-5",
        name: "GPT-5",
        provider: "OpenAI",
        status: "active",
        context: "256k",
        priceIn: 5.00,
        priceOut: 15.00,
        speed: 80,
        intelligence: 98,
        pros: ["Next-gen reasoning", "Multimodal native", "Deep agentic capabilities"],
        cons: ["Expensive", "High demand"],
        apiUrl: "https://api.openai.com/v1/chat/completions"
    },
    {
        id: "claude-3-5-opus",
        name: "Claude 3.5 Opus",
        provider: "Anthropic",
        status: "active",
        context: "200k",
        priceIn: 15.00,
        priceOut: 75.00,
        speed: 40,
        intelligence: 99,
        pros: ["Unmatched nuance", "Huge context", "Enterprise grade safety"],
        cons: ["Very expensive", "Slower inference"],
        apiUrl: "https://api.anthropic.com/v1/messages"
    },
    {
        id: "gemini-2-5-pro",
        name: "Gemini 2.5 Pro",
        provider: "Google",
        status: "active",
        context: "2M",
        priceIn: 2.50,
        priceOut: 10.00,
        speed: 70,
        intelligence: 96,
        pros: ["Massive 2M context", "Deep Google ecosystem integration", "Multimodal"],
        cons: ["Latency can vary", "Strict safety filters"],
        apiUrl: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent"
    },
    {
        id: "llama-4-405b",
        name: "Llama 4 405B",
        provider: "Meta (via Groq)",
        status: "active",
        context: "128k",
        priceIn: 2.00,
        priceOut: 2.00,
        speed: 85,
        intelligence: 95,
        pros: ["Open Source King", "Rivals proprietary models", "Flexible deployment"],
        cons: ["Heavy hardware requirements", "Complex to self-host"],
        apiUrl: "https://api.groq.com/openai/v1/chat/completions"
    },
    {
        id: "mistral-large-2",
        name: "Mistral Large 2",
        provider: "Mistral AI",
        status: "active",
        context: "128k",
        priceIn: 2.00,
        priceOut: 6.00,
        speed: 80,
        intelligence: 92,
        pros: ["Strong coding abilities", "European data privacy", "Concise outputs"],
        cons: ["Pricey compared to Llama", "Smaller ecosystem"],
        apiUrl: "https://api.mistral.ai/v1/chat/completions"
    },
    {
        id: "gpt-4o",
        name: "GPT-4o",
        provider: "OpenAI",
        status: "active",
        context: "128k",
        priceIn: 2.50,
        priceOut: 10.00,
        speed: 90,
        intelligence: 96,
        pros: ["Extremely fast latency", "Great tool use", "Cheaper than Sonnet"],
        cons: ["Slightly weaker logic", "Verbose output"],
        apiUrl: "https://api.openai.com/v1/chat/completions"
    },
    {
        id: "claude-3-5-sonnet",
        name: "Claude 3.5 Sonnet",
        provider: "Anthropic",
        status: "active",
        context: "200k",
        priceIn: 3.00,
        priceOut: 15.00,
        speed: 75,
        intelligence: 98,
        pros: ["Best-in-class reasoning", "Huge 200k context", "Low hallucination"],
        cons: ["More expensive than GPT-4o", "Strict rate limits"],
        apiUrl: "https://api.anthropic.com/v1/messages"
    },
    {
        id: "gemini-2-5-flash",
        name: "Gemini 2.5 Flash",
        provider: "Google",
        status: "active",
        context: "1M",
        priceIn: 0.10,
        priceOut: 0.40,
        speed: 95,
        intelligence: 85,
        pros: ["Cheapest major model", "1M Context Window", "Multimodal native"],
        cons: ["Lower reasoning capability", "Can be verbose"],
        apiUrl: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
    },
    {
        id: "command-r-plus",
        name: "Command R+",
        provider: "Cohere",
        status: "active",
        context: "128k",
        priceIn: 3.00,
        priceOut: 15.00,
        speed: 85,
        intelligence: 90,
        pros: ["Best for RAG", "Citations included", "Enterprise focused"],
        cons: ["Not a generalist", "Complex pricing"],
        apiUrl: "https://api.cohere.com/v1/chat"
    },
    {
        id: "ibm-granite-3",
        name: "IBM Granite 3",
        provider: "IBM Watson",
        status: "active",
        context: "128k",
        priceIn: 1.50,
        priceOut: 1.50,
        speed: 80,
        intelligence: 88,
        pros: ["Enterprise focused", "IT automation specialist", "Open source"],
        cons: ["Niche use cases", "Less general knowledge"],
        apiUrl: "https://us-south.ml.cloud.ibm.com/ml/v1/text/generation"
    },
    {
        id: "perplexity-sonar",
        name: "Perplexity Sonar",
        provider: "Perplexity",
        status: "active",
        context: "128k",
        priceIn: 1.00,
        priceOut: 1.00,
        speed: 90,
        intelligence: 92,
        pros: ["Real-time web search", "Fact-based answers", "Citations included"],
        cons: ["Search focused", "Variable reasoning"],
        apiUrl: "https://api.perplexity.ai/chat/completions"
    },
    {
        id: "deepseek-v3",
        name: "DeepSeek V3",
        provider: "DeepSeek",
        status: "active",
        context: "128k",
        priceIn: 0.14,
        priceOut: 0.28,
        speed: 85,
        intelligence: 94,
        pros: ["Unbeatable price (20x cheaper)", "Open Weights", "Rivals GPT-4"],
        cons: ["Data privacy concerns", "API stability varies"],
        apiUrl: "https://api.deepseek.com/chat/completions"
    },
    // GRAVEYARD
    {
        id: "gpt-3.5-turbo",
        name: "GPT-3.5 Turbo",
        provider: "OpenAI",
        status: "legacy",
        context: "16k",
        priceIn: 0.50,
        priceOut: 1.50,
        speed: 95,
        intelligence: 70,
        pros: ["Was the standard"],
        cons: ["Superseded", "High hallucination"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "claude-2",
        name: "Claude 2.1",
        provider: "Anthropic",
        status: "legacy",
        context: "200k",
        priceIn: 8.00,
        priceOut: 24.00,
        speed: 40,
        intelligence: 80,
        pros: ["First 200k model"],
        cons: ["Very lazy", "Expensive"],
        apiUrl: "DEPRECATED"
    }
];
