// --- DATA STORE ---
// Last updated: July 2026 | Sources: OpenAI, Anthropic, Google, Mistral, DeepSeek, Meta official docs
const db = [
    // ═══════════════════════════════
    //  ACTIVE MODELS
    // ═══════════════════════════════

    // ── OpenAI ──────────────────────
    {
        id: "gpt-5-6-sol",
        name: "GPT-5.6 Sol",
        provider: "OpenAI",
        status: "active",
        context: "256k",
        priceIn: 5.00,
        priceOut: 30.00,
        speed: 75,
        intelligence: 99,
        pros: ["Flagship GPT-5.6 tier", "Frontier reasoning & agentic tasks", "Multimodal native", "Deep coding capability"],
        cons: ["Most expensive OpenAI model", "Slower than lower tiers", "High demand at peak times"],
        apiUrl: "https://api.openai.com/v1/chat/completions"
    },
    {
        id: "gpt-5-6-terra",
        name: "GPT-5.6 Terra",
        provider: "OpenAI",
        status: "active",
        context: "256k",
        priceIn: 2.50,
        priceOut: 15.00,
        speed: 84,
        intelligence: 96,
        pros: ["GPT-5.6 at mid-tier cost", "Strong reasoning & coding", "Competitive with previous flagships", "Prompt caching support"],
        cons: ["Pricier than GPT-4.1 for most tasks", "Sol outperforms on hardest tasks"],
        apiUrl: "https://api.openai.com/v1/chat/completions"
    },
    {
        id: "gpt-5-6-luna",
        name: "GPT-5.6 Luna",
        provider: "OpenAI",
        status: "active",
        context: "256k",
        priceIn: 1.00,
        priceOut: 6.00,
        speed: 91,
        intelligence: 91,
        pros: ["Most affordable GPT-5.6 tier", "Fast latency", "Great for high-volume pipelines", "Strong instruction following"],
        cons: ["Less capable than Sol/Terra on complex tasks", "Thinking limited vs full Sol"],
        apiUrl: "https://api.openai.com/v1/chat/completions"
    },


    // ── Anthropic ───────────────────
    {
        id: "claude-fable-5",
        name: "Claude Fable 5",
        provider: "Anthropic",
        status: "active",
        context: "1M",
        priceIn: 10.00,
        priceOut: 50.00,
        speed: 60,
        intelligence: 99,
        pros: ["Anthropic's most capable model", "1M token context window", "Exceptional autonomous & agentic tasks", "Frontier safety alignment"],
        cons: ["Premium pricing ($10/$50 per MTok)", "Slower generation speed", "Overkill for routine tasks"],
        apiUrl: "https://api.anthropic.com/v1/messages"
    },
    {
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        provider: "Anthropic",
        status: "active",
        context: "1M",
        priceIn: 5.00,
        priceOut: 25.00,
        speed: 68,
        intelligence: 97,
        pros: ["1M token context at half of Fable 5 cost", "Flagship for agentic coding", "Default high-effort reasoning mode", "Claude Code optimized"],
        cons: ["High cost for standard chatbot use", "Slower than Sonnet models"],
        apiUrl: "https://api.anthropic.com/v1/messages"
    },
    {
        id: "claude-sonnet-5",
        name: "Claude Sonnet 5",
        provider: "Anthropic",
        status: "active",
        context: "200k",
        priceIn: 2.00,
        priceOut: 10.00,
        speed: 78,
        intelligence: 96,
        pros: ["Introductory pricing through Aug 2026", "Excellent coding & analysis", "Low hallucination rate", "Fast enough for prod workloads"],
        cons: ["Intro pricing rises to $3/$15 post-Aug 2026", "200k context only (vs Opus 1M)"],
        apiUrl: "https://api.anthropic.com/v1/messages"
    },
    {
        id: "claude-sonnet-4.6",
        name: "Claude Sonnet 4.6",
        provider: "Anthropic",
        status: "active",
        context: "200k",
        priceIn: 3.00,
        priceOut: 15.00,
        speed: 75,
        intelligence: 94,
        pros: ["Proven stable workhorse", "200k context window", "Reliable for enterprise workloads", "Broad platform availability"],
        cons: ["More expensive than Sonnet 5 at intro pricing", "Not the latest generation"],
        apiUrl: "https://api.anthropic.com/v1/messages"
    },
    {
        id: "claude-haiku-4.5",
        name: "Claude Haiku 4.5",
        provider: "Anthropic",
        status: "active",
        context: "200k",
        priceIn: 1.00,
        priceOut: 5.00,
        speed: 93,
        intelligence: 85,
        pros: ["Fastest Anthropic model", "200k context window", "Cost-effective for chatbots & classification", "Strong tool use"],
        cons: ["Lower reasoning ceiling than Sonnet", "Not suited for complex agentic multi-step flows"],
        apiUrl: "https://api.anthropic.com/v1/messages"
    },

    // ── Google ───────────────────────
    {
        id: "gemini-3-5-flash",
        name: "Gemini 3.5 Flash",
        provider: "Google",
        status: "active",
        context: "1M",
        priceIn: 1.50,
        priceOut: 9.00,
        speed: 92,
        intelligence: 94,
        pros: ["Google's latest flagship Flash model", "1M token context window", "Superior search & grounding integration", "Multimodal native"],
        cons: ["Higher output price than Gemini 2.5 Flash", "Thinking tokens included in output billing"],
        apiUrl: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent"
    },
    {
        id: "gemini-3-1-pro",
        name: "Gemini 3.1 Pro",
        provider: "Google",
        status: "active",
        context: "1M",
        priceIn: 2.00,
        priceOut: 12.00,
        speed: 72,
        intelligence: 96,
        pros: ["Top multimodal understanding", "Best vibe-coding & agentic capabilities", "Deep Google ecosystem integration", "Code generation leader"],
        cons: ["Premium pricing tier", "Latency can vary under high load"],
        apiUrl: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-pro-preview:generateContent"
    },
    {
        id: "gemini-3-1-flash-lite",
        name: "Gemini 3.1 Flash-Lite",
        provider: "Google",
        status: "active",
        context: "1M",
        priceIn: 0.25,
        priceOut: 1.50,
        speed: 97,
        intelligence: 83,
        pros: ["Ultra-low cost for high-volume agentic tasks", "1M context at minimal price", "Great for translation & data processing", "Free tier available"],
        cons: ["Lower intelligence ceiling", "Not suited for complex reasoning"],
        apiUrl: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent"
    },


    // ── Meta (Open Source) ──────────
    {
        id: "llama-4-maverick",
        name: "Llama 4 Maverick",
        provider: "Meta (via Groq/Together)",
        status: "active",
        context: "1M",
        priceIn: 0.50,
        priceOut: 0.77,
        speed: 88,
        intelligence: 93,
        pros: ["Open-weights MoE powerhouse", "Rivals proprietary frontier models", "Flexible self-hosting", "128 expert architecture"],
        cons: ["Heavy hardware requirements for self-hosting", "Context quality degrades at extremes"],
        apiUrl: "https://api.groq.com/openai/v1/chat/completions"
    },
    {
        id: "llama-4-scout",
        name: "Llama 4 Scout",
        provider: "Meta (via Groq/Together)",
        status: "active",
        context: "10M",
        priceIn: 0.11,
        priceOut: 0.34,
        speed: 93,
        intelligence: 86,
        pros: ["10M token context (world record)", "Ultra-cheap inference", "Efficient MoE architecture", "Open weights"],
        cons: ["Lower raw reasoning than Maverick", "Self-hosting requires significant VRAM"],
        apiUrl: "https://api.groq.com/openai/v1/chat/completions"
    },

    // ── Mistral AI ──────────────────
    {
        id: "mistral-medium-3-5",
        name: "Mistral Medium 3.5",
        provider: "Mistral AI",
        status: "active",
        context: "256k",
        priceIn: 1.50,
        priceOut: 7.50,
        speed: 82,
        intelligence: 93,
        pros: ["Balanced flagship for general-purpose tasks", "256k context window", "Strong coding & reasoning", "GDPR-compliant European AI"],
        cons: ["Mid-tier pricing for mid-tier capability", "Smaller ecosystem vs OpenAI/Anthropic"],
        apiUrl: "https://api.mistral.ai/v1/chat/completions"
    },
    {
        id: "mistral-small-4",
        name: "Mistral Small 4",
        provider: "Mistral AI",
        status: "active",
        context: "128k",
        priceIn: 0.15,
        priceOut: 0.60,
        speed: 94,
        intelligence: 86,
        pros: ["Extremely competitive price at $0.15/M input", "Fast latency", "Great for high-volume classification & chatbots", "50% batch discount available"],
        cons: ["Limited context vs Large 3", "Less capable on complex multi-step tasks"],
        apiUrl: "https://api.mistral.ai/v1/chat/completions"
    },
    {
        id: "mistral-large-3",
        name: "Mistral Large 3",
        provider: "Mistral AI",
        status: "active",
        context: "256k",
        priceIn: 0.50,
        priceOut: 1.50,
        speed: 88,
        intelligence: 92,
        pros: ["Best Mistral value flagship", "Massive 256k context", "Strong coding & tool use", "GDPR-compliant by design"],
        cons: ["Smaller ecosystem than OpenAI/Anthropic", "Less agentic tooling vs Mistral Medium 3.5"],
        apiUrl: "https://api.mistral.ai/v1/chat/completions"
    },
    {
        id: "codestral-2",
        name: "Codestral 2",
        provider: "Mistral AI",
        status: "active",
        context: "128k",
        priceIn: 0.30,
        priceOut: 0.90,
        speed: 93,
        intelligence: 90,
        pros: ["Code-specialist at ultra-low cost", "Fast FIM (fill-in-the-middle) support", "128k context for large codebases", "Outperforms models 3x its cost on code"],
        cons: ["Primarily code-focused", "Less general-purpose than Large models"],
        apiUrl: "https://api.mistral.ai/v1/chat/completions"
    },

    // ── DeepSeek ────────────────────
    {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        provider: "DeepSeek",
        status: "active",
        context: "128k",
        priceIn: 0.14,
        priceOut: 0.28,
        speed: 87,
        intelligence: 92,
        pros: ["Unbeatable price-to-performance ratio", "Open weights available", "Integrated thinking mode", "Rivals frontier models on many benchmarks"],
        cons: ["Data privacy concerns (Chinese origin)", "Peak-hour pricing applies", "API stability varies"],
        apiUrl: "https://api.deepseek.com/chat/completions"
    },
    {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        provider: "DeepSeek",
        status: "active",
        context: "128k",
        priceIn: 0.44,
        priceOut: 0.87,
        speed: 78,
        intelligence: 95,
        pros: ["Frontier-class reasoning at fraction of proprietary cost", "MoE architecture", "Extended thinking mode", "Open weights"],
        cons: ["Data privacy & geopolitical concerns", "Peak-hour 2x pricing surge", "Context limited vs Anthropic/Google"],
        apiUrl: "https://api.deepseek.com/chat/completions"
    },

    // ── xAI ─────────────────────────
    {
        id: "grok-4-5",
        name: "Grok 4.5",
        provider: "xAI",
        status: "active",
        context: "500k",
        priceIn: 2.00,
        priceOut: 6.00,
        speed: 80,
        intelligence: 96,
        pros: ["xAI flagship (July 2026)", "500k context window", "Optimized for coding & agentic tasks", "V9 foundation — 1.5T parameter scale"],
        cons: ["Context smaller than Grok 4.20 variant", "Newer model, ecosystem still maturing"],
        apiUrl: "https://api.x.ai/v1/chat/completions"
    },
    {
        id: "grok-4-1-fast",
        name: "Grok 4.1 Fast",
        provider: "xAI",
        status: "active",
        context: "2M",
        priceIn: 0.20,
        priceOut: 0.50,
        speed: 96,
        intelligence: 88,
        pros: ["Massive 2M context at ultra-low cost", "$0.20/M input — extremely budget-friendly", "Built for high-throughput pipelines", "Fast response times"],
        cons: ["Less capable than Grok 4.5 on complex tasks", "Not suited for frontier reasoning"],
        apiUrl: "https://api.x.ai/v1/chat/completions"
    },

    // ── Alibaba Cloud (Qwen) ─────────
    {
        id: "qwen3-7-max",
        name: "Qwen3.7-Max",
        provider: "Alibaba Cloud",
        status: "active",
        context: "1M",
        priceIn: 1.25,
        priceOut: 3.75,
        speed: 78,
        intelligence: 95,
        pros: ["Alibaba's flagship reasoning model", "1M token context window", "Hybrid thinking mode (on/off)", "Competitive with frontier models on benchmarks"],
        cons: ["Data sovereignty concerns", "International pricing higher than Chinese mainland", "Ecosystem primarily Chinese-centric"],
        apiUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    },
    {
        id: "qwen3-7-plus",
        name: "Qwen3.7-Plus",
        provider: "Alibaba Cloud",
        status: "active",
        context: "1M",
        priceIn: 0.32,
        priceOut: 1.28,
        speed: 89,
        intelligence: 90,
        pros: ["1M context at very low cost", "Strong balance of speed & capability", "Hybrid thinking mode", "OpenAI-compatible API"],
        cons: ["Data sovereignty concerns", "Less ecosystem support outside of China"],
        apiUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    },

    // ── Cohere ───────────────────────
    {
        id: "command-a-plus",
        name: "Command A+",
        provider: "Cohere",
        status: "active",
        context: "128k",
        priceIn: 2.50,
        priceOut: 10.00,
        speed: 84,
        intelligence: 92,
        pros: ["Cohere's flagship MoE model (May 2026)", "Best-in-class RAG with built-in citations", "Multimodal vision input support", "Enterprise-grade on 1x B200 or 2x H100 GPUs"],
        cons: ["Specialized for enterprise/RAG; weaker as generalist", "Pricing rivals frontier models"],
        apiUrl: "https://api.cohere.com/v2/chat"
    },

    // ── Specialized ─────────────────
    {
        id: "perplexity-sonar",
        name: "Perplexity Sonar",
        provider: "Perplexity",
        status: "active",
        context: "128k",
        priceIn: 1.00,
        priceOut: 1.00,
        speed: 91,
        intelligence: 92,
        pros: ["Real-time web search baked in", "Fact-grounded answers with citations", "Great for research assistants", "Fast responses"],
        cons: ["Search-focused design", "Variable reasoning depth", "Less suited for pure generation tasks"],
        apiUrl: "https://api.perplexity.ai/chat/completions"
    },


    // ═══════════════════════════════
    //  GRAVEYARD (DEPRECATED)
    // ═══════════════════════════════
    {
        id: "gpt-5",
        name: "GPT-5",
        provider: "OpenAI",
        status: "legacy",
        context: "256k",
        priceIn: 5.00,
        priceOut: 15.00,
        speed: 80,
        intelligence: 98,
        pros: ["Was OpenAI's flagship in early 2026", "Strong multimodal & reasoning"],
        cons: ["Superseded by GPT-5.6 family (Sol/Terra/Luna)", "No longer recommended for new integrations"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "gpt-4.1",
        name: "GPT-4.1",
        provider: "OpenAI",
        status: "legacy",
        context: "1M",
        priceIn: 2.00,
        priceOut: 8.00,
        speed: 88,
        intelligence: 95,
        pros: ["Had massive 1M token context", "Best-in-class instruction following at launch"],
        cons: ["Retired from ChatGPT Feb 2026", "API shutdown Oct 2026 — migrate to GPT-5.6"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "gpt-4.1-mini",
        name: "GPT-4.1 Mini",
        provider: "OpenAI",
        status: "legacy",
        context: "1M",
        priceIn: 0.40,
        priceOut: 1.60,
        speed: 95,
        intelligence: 88,
        pros: ["Was a fast, affordable 1M context model"],
        cons: ["Retired Feb 2026 alongside GPT-4.1", "API fully shut down — use GPT-5.6 Luna instead"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "o4-mini",
        name: "o4-mini",
        provider: "OpenAI",
        status: "legacy",
        context: "200k",
        priceIn: 1.10,
        priceOut: 4.40,
        speed: 50,
        intelligence: 97,
        pros: ["Was a strong affordable reasoning model", "Top math & science benchmark scores"],
        cons: ["Retired from ChatGPT Feb 2026", "API shutdown Oct 23, 2026"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "gemini-2-5-pro",
        name: "Gemini 2.5 Pro",
        provider: "Google",
        status: "legacy",
        context: "2M",
        priceIn: 2.50,
        priceOut: 10.00,
        speed: 70,
        intelligence: 95,
        pros: ["Had massive 2M context window", "Strong multimodal & reasoning in its era"],
        cons: ["Retirement scheduled Oct 16, 2026", "Replaced by Gemini 3.1 Pro"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "gemini-2-5-flash",
        name: "Gemini 2.5 Flash",
        provider: "Google",
        status: "legacy",
        context: "1M",
        priceIn: 0.10,
        priceOut: 0.40,
        speed: 96,
        intelligence: 86,
        pros: ["Was one of cheapest major models", "Hybrid reasoning with thinking budgets"],
        cons: ["Retirement scheduled Oct 16, 2026", "Migrate to Gemini 3.5 Flash or 3.1 Flash-Lite"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "ibm-granite-3",
        name: "IBM Granite 3",
        provider: "IBM Watson",
        status: "legacy",
        context: "128k",
        priceIn: 1.50,
        priceOut: 1.50,
        speed: 80,
        intelligence: 88,
        pros: ["Was enterprise-grade for IT automation", "Fully open source with transparent training data"],
        cons: ["Superseded by IBM Granite 4.1 (April 2026)", "Granite 4.1 has 512k context vs 128k"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "command-r-plus",
        name: "Command R+",
        provider: "Cohere",
        status: "legacy",
        context: "128k",
        priceIn: 3.00,
        priceOut: 15.00,
        speed: 85,
        intelligence: 90,
        pros: ["Was best-in-class for RAG pipelines", "Built-in citation generation"],
        cons: ["Superseded by Command A+ (May 2026)", "Higher cost than its successor"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "claude-3-5-sonnet",
        name: "Claude 3.5 Sonnet",
        provider: "Anthropic",
        status: "legacy",
        context: "200k",
        priceIn: 3.00,
        priceOut: 15.00,
        speed: 75,
        intelligence: 95,
        pros: ["Was best-in-class for coding in 2025", "Huge 200k context"],
        cons: ["Officially retired 2026", "Replaced by Sonnet 5 and Opus 4.8"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "gpt-4o",
        name: "GPT-4o",
        provider: "OpenAI",
        status: "legacy",
        context: "128k",
        priceIn: 2.50,
        priceOut: 10.00,
        speed: 90,
        intelligence: 93,
        pros: ["Was extremely fast & multimodal", "Dominated 2024-2025 benchmarks"],
        cons: ["Retired from ChatGPT Feb 2026", "Fully succeeded by GPT-4.1 and GPT-5.6 series"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "mistral-large-2",
        name: "Mistral Large 2",
        provider: "Mistral AI",
        status: "legacy",
        context: "128k",
        priceIn: 2.00,
        priceOut: 6.00,
        speed: 80,
        intelligence: 90,
        pros: ["Was strong European option", "128k context & good coding"],
        cons: ["Superseded by Mistral Large 3 (better & cheaper)", "No longer recommended for new projects"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "gpt-3.5-turbo",
        name: "GPT-3.5 Turbo",
        provider: "OpenAI",
        status: "legacy",
        context: "16k",
        priceIn: 0.50,
        priceOut: 1.50,
        speed: 95,
        intelligence: 70,
        pros: ["Was the industry standard in 2023-2024", "Extremely fast"],
        cons: ["Superseded entirely", "High hallucination rate", "Tiny context window"],
        apiUrl: "DEPRECATED"
    },
    {
        id: "claude-2",
        name: "Claude 2.1",
        provider: "Anthropic",
        status: "legacy",
        context: "200k",
        priceIn: 8.00,
        priceOut: 24.00,
        speed: 40,
        intelligence: 80,
        pros: ["Was first model with 200k context", "Pioneered long-context AI"],
        cons: ["Very lazy output quality", "Extremely expensive", "Fully superseded"],
        apiUrl: "DEPRECATED"
    }
];
